In [60]:
# Import Libiries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [61]:
# Import the dataset
df = pd.read_csv('personality_dataset.csv')
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [62]:
# Display columns
df.columns

Index(['Time_spent_Alone', 'Stage_fear', 'Social_event_attendance',
       'Going_outside', 'Drained_after_socializing', 'Friends_circle_size',
       'Post_frequency', 'Personality'],
      dtype='object')

In [63]:
df.shape

(2900, 8)

In [64]:
# Data type
df.dtypes

Time_spent_Alone             float64
Stage_fear                    object
Social_event_attendance      float64
Going_outside                float64
Drained_after_socializing     object
Friends_circle_size          float64
Post_frequency               float64
Personality                   object
dtype: object

In [65]:
# Check null values
df.isnull().sum()

Time_spent_Alone             63
Stage_fear                   73
Social_event_attendance      62
Going_outside                66
Drained_after_socializing    52
Friends_circle_size          77
Post_frequency               65
Personality                   0
dtype: int64

In [66]:
# Check the percentage of null values
null_summary = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': df.isnull().mean() * 100
}).sort_values(by='Percentage', ascending=False)

print(null_summary)

                           Missing Values  Percentage
Friends_circle_size                    77    2.655172
Stage_fear                             73    2.517241
Going_outside                          66    2.275862
Post_frequency                         65    2.241379
Time_spent_Alone                       63    2.172414
Social_event_attendance                62    2.137931
Drained_after_socializing              52    1.793103
Personality                             0    0.000000

In [67]:
# Column types
num_cols = [
    'Time_spent_Alone',
    'Social_event_attendance',
    'Going_outside',
    'Friends_circle_size',
    'Post_frequency'
]

cat_cols = [
    'Stage_fear',
    'Drained_after_socializing'
]

In [68]:
# Handling Numerical columns
for col in num_cols:
  df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_607/274828889.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [69]:
# Handling Categorical columns
for col in cat_cols:
  df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_607/4095967825.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [70]:
df.isnull().sum()

Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [71]:
df['Personality'].value_counts(dropna=False)

Personality
Extrovert    1491
Introvert    1409
Name: count, dtype: int64

In [72]:
# Convert Categorical columns
df["Stage_fear"] = df["Stage_fear"].map(
    {
        "Yes": 1,
        "No": 0
    }
)


df["Drained_after_socializing"] = df["Drained_after_socializing"].map(
    {
        "Yes": 1,
        "No": 0
    }
)

In [73]:
# Encode the target column
le = LabelEncoder()
df["Personality"] = le.fit_transform(df["Personality"])

In [74]:
# Save clean dataset
df.to_csv("cleaned_dataset.csv", index=False)